server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_system?serverTimezone=GMT%2B8
    username: root
    password: 1249
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  type-aliases-package: com.mediocre.music.bean
#  mapper-locations: classpath:../com/example/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true